#! /bin/bash

#for ((x = 1; x <= 2; x++))
for ((x = 1; x <= 100; x++))
do
	echo "game $x";
	./generator --big-superposition > maps/bigsup;
	time ./lem-in < maps/bigsup > maps/ress;
	self=$(cat maps/ress | wc -l);
	echo -e "$self";
	expected=$(head -n2 maps/bigsup |  grep -e '^#' | cut -d" " -f8);
	echo -e "$expected";
	res=$(($self - $expected));
	#echo -e "$res";
	res=$(echo "$self - $expected" | bc);
	echo "$self - $expected" | bc;
	if [[ "$res" > "10" ]];
	then
		echo "BAD";
	else
		echo "GOOD"
	fi
done
