#! /bin/bash
read -e -p "how many try should be tested?  " TURNS

for ((x = 1; x <= $TURNS; x++))
do
	echo "turn $x";
	./generator --big-superposition > maps/bigsup;
	./lem-in -n < maps/bigsup > maps/ress;
	result=$(tail -n1 maps/ress);
	expected=$(tail -n1 maps/bigsup| cut -d" " -f8);
	echo "turns expected is $expected";
	echo "$result"
done
